# Generated by Django 5.1.4 on 2025-01-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_session_remove_answer_text_answer_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='origin_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_sessions', to='myapp.session'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('session', 'question')},
        ),
    ]
