services:
  - name: backend
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    build:
      context: ./backend
    envVars:
      - key: DATABASE_URL
        value: postgres://postgres:postgres@db.internal:5432/postgres
    plan: free
    healthCheckPath: /

  - name: frontend
    type: web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    build:
      context: ./frontend
    envVars:
      - key: VUE_APP_API_URL
        value: https://backend.onrender.com
    staticPublishPath: ./dist
    plan: free

